### ISSUE TITLE
Error with html-css when run config

### ISSUE THREAD

**Issue by mcp1766** [Jezda1337/nvim-html-css#27] opened 2024-08-18 18:13 UTC
I receive this message 

![Capture d’écran du 2024-08-18 23-58-10](https://github.com/user-attachments/assets/4e2bfc8f-52db-4a12-a65d-43edcc9961f3)

**Comment by Jezda1337** [comment] 2024-08-19 07:52
Unfortunately, this is a known issue with a ton of files, this issue is fixed in v2. You may want to check it out: https://github.com/Jezda1337/nvim-html-css/tree/v2. However, bdw v2 is still in development mode, and I'm slowly working on it.

**Comment by ricardoantonio** [comment] 2024-11-09 08:25
So, no solution until v2?

**Comment by Jezda1337** [comment] 2024-11-09 16:00
@ricardoantonio do you have the same error message? what neovim version are you using?

**Comment by ricardoantonio** [comment] 2024-11-09 16:09
I'm using neovim 10.2

**Comment by Jezda1337** [comment] 2024-11-09 19:50
I could only reproduce this issue when initializing the htm-css plugin before the CMP plugin. Can someone share the configuration so I can check it?

**Comment by ricardoantonio** [comment] 2024-11-10 00:33
I tried with this two configs

```lua
return {
  {
    'hrsh7th/nvim-cmp',
    event = 'InsertEnter',
    dependencies = {
      -- Snippet Engine & its associated nvim-cmp source
      {
        'L3MON4D3/LuaSnip',
        build = (function()
          -- Build Step is needed for regex support in snippets.
          -- This step is not supported in many windows environments.
          -- Remove the below condition to re-enable on windows.
          if vim.fn.has 'win32' == 1 or vim.fn.executable 'make' == 0 then
            return
          end
          return 'make install_jsregexp'
        end)(),
        dependencies = {
          -- `friendly-snippets` contains a variety of premade snippets.
          --    See the README about individual language/framework/plugin snippets:
          --    https://github.com/rafamadriz/friendly-snippets
          -- {
          --   'rafamadriz/friendly-snippets',
          --   config = function()
          --     require('luasnip.loaders.from_vscode').lazy_load()
          --   end,
          -- },
        },
      },
      'saadparwaiz1/cmp_luasnip',

      'hrsh7th/cmp-nvim-lsp',
      'hrsh7th/cmp-path',

      'luckasRanarison/tailwind-tools.nvim', -- Add tailwind colors to completion items
      'onsails/lspkind-nvim', -- Add icons to completion items
    },
    config = function()
      -- See `:help cmp`
      local cmp = require 'cmp'
      local luasnip = require 'luasnip'
      luasnip.config.setup {}
      cmp.setup {
        snippet = {
          expand = function(args)
            luasnip.lsp_expand(args.body)
          end,
        },
        completion = { completeopt = 'menu,menuone,noinsert' },

        -- For an understanding of why these mappings were
        -- chosen, you will need to read `:help ins-completion`
        --
        -- No, but seriously. Please read `:help ins-completion`, it is really good!
        mapping = cmp.mapping.preset.insert {
          -- Select the [n]ext item
          ['<C-n>'] = cmp.mapping.select_next_item(),
          -- Select the [p]revious item
          ['<C-p>'] = cmp.mapping.select_prev_item(),

          -- Scroll the documentation window [b]ack / [f]orward
          ['<C-b>'] = cmp.mapping.scroll_docs(-4),
          ['<C-f>'] = cmp.mapping.scroll_docs(4),

          -- Accept ([y]es) the completion.
          --  This will auto-import if your LSP supports it.
          --  This will expand snippets if the LSP sent a snippet.
          ['<C-y>'] = cmp.mapping.confirm { select = true },

          -- If you prefer more traditional completion keymaps,
          -- you can uncomment the following lines
          --['<CR>'] = cmp.mapping.confirm { select = true },
          --['<Tab>'] = cmp.mapping.select_next_item(),
          --['<S-Tab>'] = cmp.mapping.select_prev_item(),

          -- Manually trigger a completion from nvim-cmp.
          --  Generally you don't need this, because nvim-cmp will display
          --  completions whenever it has completion options available.
          ['<C-Space>'] = cmp.mapping.complete {},

          -- Think of <c-l> as moving to the right of your snippet expansion.
          --  So if you have a snippet that's like:
          --  function $name($args)
          --    $body
          --  end
          --
          -- <c-l> will move you to the right of each of the expansion locations.
          -- <c-h> is similar, except moving you backwards.
          ['<C-l>'] = cmp.mapping(function()
            if luasnip.expand_or_locally_jumpable() then
              luasnip.expand_or_jump()
            end
          end, { 'i', 's' }),
          ['<C-h>'] = cmp.mapping(function()
            if luasnip.locally_jumpable(-1) then
              luasnip.jump(-1)
            end
          end, { 'i', 's' }),

          -- For more advanced Luasnip keymaps (e.g. selecting choice nodes, expansion) see:
          --    https://github.com/L3MON4D3/LuaSnip?tab=readme-ov-file#keymaps
        },
        sources = {
          {
            name = 'lazydev',
            -- set group index to 0 to skip loading LuaLS completions as lazydev recommends it
            group_index = 0,
          },
          { name = 'nvim_lsp' },
          { name = 'luasnip' },
          { name = 'path' },
          {
            name = 'html-css',
            option = {
              -- your configuration here
            },
          },
        },
        formatting = {
          format = require('lspkind').cmp_format {
            mode = 'symbol_text',
            menu = {
              buffer = '[Buffer]',
              nvim_lsp = '[LSP]',
              luasnip = '[LuaSnip]',
              nvim_lua = '[Lua]',
              latex_symbols = '[Latex]',
              path = '[Path]',
            },
            before = require('tailwind-tools.cmp').lspkind_format, -- Add tailwind colors
          },
        },
      }
    end,
  },
  {
    'Jezda1337/nvim-html-css',
    dependencies = {
      'nvim-treesitter/nvim-treesitter',
      'nvim-lua/plenary.nvim',
    },
    config = function()
      require('html-css'):setup()
    end,
  },
}
```

```lua
return {
  {
    'hrsh7th/nvim-cmp',
    event = 'InsertEnter',
    dependencies = {
      -- Snippet Engine & its associated nvim-cmp source
      {
        'L3MON4D3/LuaSnip',
        build = (function()
          -- Build Step is needed for regex support in snippets.
          -- This step is not supported in many windows environments.
          -- Remove the below condition to re-enable on windows.
          if vim.fn.has 'win32' == 1 or vim.fn.executable 'make' == 0 then
            return
          end
          return 'make install_jsregexp'
        end)(),
        dependencies = {
          -- `friendly-snippets` contains a variety of premade snippets.
          --    See the README about individual language/framework/plugin snippets:
          --    https://github.com/rafamadriz/friendly-snippets
          -- {
          --   'rafamadriz/friendly-snippets',
          --   config = function()
          --     require('luasnip.loaders.from_vscode').lazy_load()
          --   end,
          -- },
        },
      },
      'saadparwaiz1/cmp_luasnip',

      'hrsh7th/cmp-nvim-lsp',
      'hrsh7th/cmp-path',

      'luckasRanarison/tailwind-tools.nvim', -- Add tailwind colors to completion items
      'onsails/lspkind-nvim', -- Add icons to completion items
      {
        'Jezda1337/nvim-html-css',
        dependencies = {
          'nvim-treesitter/nvim-treesitter',
          'nvim-lua/plenary.nvim',
        },
        config = function()
          require('html-css'):setup()
        end,
      },
    },
    config = function()
      -- See `:help cmp`
      local cmp = require 'cmp'
      local luasnip = require 'luasnip'
      luasnip.config.setup {}
      cmp.setup {
        snippet = {
          expand = function(args)
            luasnip.lsp_expand(args.body)
          end,
        },
        completion = { completeopt = 'menu,menuone,noinsert' },

        -- For an understanding of why these mappings were
        -- chosen, you will need to read `:help ins-completion`
        --
        -- No, but seriously. Please read `:help ins-completion`, it is really good!
        mapping = cmp.mapping.preset.insert {
          -- Select the [n]ext item
          ['<C-n>'] = cmp.mapping.select_next_item(),
          -- Select the [p]revious item
          ['<C-p>'] = cmp.mapping.select_prev_item(),

          -- Scroll the documentation window [b]ack / [f]orward
          ['<C-b>'] = cmp.mapping.scroll_docs(-4),
          ['<C-f>'] = cmp.mapping.scroll_docs(4),

          -- Accept ([y]es) the completion.
          --  This will auto-import if your LSP supports it.
          --  This will expand snippets if the LSP sent a snippet.
          ['<C-y>'] = cmp.mapping.confirm { select = true },

          -- If you prefer more traditional completion keymaps,
          -- you can uncomment the following lines
          --['<CR>'] = cmp.mapping.confirm { select = true },
          --['<Tab>'] = cmp.mapping.select_next_item(),
          --['<S-Tab>'] = cmp.mapping.select_prev_item(),

          -- Manually trigger a completion from nvim-cmp.
          --  Generally you don't need this, because nvim-cmp will display
          --  completions whenever it has completion options available.
          ['<C-Space>'] = cmp.mapping.complete {},

          -- Think of <c-l> as moving to the right of your snippet expansion.
          --  So if you have a snippet that's like:
          --  function $name($args)
          --    $body
          --  end
          --
          -- <c-l> will move you to the right of each of the expansion locations.
          -- <c-h> is similar, except moving you backwards.
          ['<C-l>'] = cmp.mapping(function()
            if luasnip.expand_or_locally_jumpable() then
              luasnip.expand_or_jump()
            end
          end, { 'i', 's' }),
          ['<C-h>'] = cmp.mapping(function()
            if luasnip.locally_jumpable(-1) then
              luasnip.jump(-1)
            end
          end, { 'i', 's' }),

          -- For more advanced Luasnip keymaps (e.g. selecting choice nodes, expansion) see:
          --    https://github.com/L3MON4D3/LuaSnip?tab=readme-ov-file#keymaps
        },
        sources = {
          {
            name = 'lazydev',
            -- set group index to 0 to skip loading LuaLS completions as lazydev recommends it
            group_index = 0,
          },
          { name = 'nvim_lsp' },
          { name = 'luasnip' },
          { name = 'path' },
          {
            name = 'html-css',
            option = {
              -- your configuration here
            },
          },
        },
        formatting = {
          format = require('lspkind').cmp_format {
            mode = 'symbol_text',
            menu = {
              buffer = '[Buffer]',
              nvim_lsp = '[LSP]',
              luasnip = '[LuaSnip]',
              nvim_lua = '[Lua]',
              latex_symbols = '[Latex]',
              path = '[Path]',
            },
            before = require('tailwind-tools.cmp').lspkind_format, -- Add tailwind colors
          },
        },
      }
    end,
  },
}
```

**Comment by Jezda1337** [comment] 2024-11-10 11:37
Is it possible to share whole neovim config? if not can you put this inside option table and try again

```lua
	enable_on = {
		"html",
	}, -- set the file types you want the plugin to work on
	dir_to_exclude = { "sdk" },
	file_extensions = { "css", "sass", "less" }, -- set the local filetypes from which you want to derive classes
	style_sheets = {
		-- example of remote styles, only css no js for now
		"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css",
		"https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css",
	},
```

**Comment by ricardoantonio** [comment] 2024-11-10 14:26
it works!
https://github.com/ricardoantonio/neovim-config/blob/main/lua/plugins/autocompletion.lua
https://github.com/ricardoantonio/neovim-config/tree/main
Is something with the `dir_to_exclude = { "sdk" },` line?

Is there a way to make it works with `jsx` and `tsx` with the `className` property?

**Comment by Jezda1337** [comment] 2024-11-10 14:37
Thanks for sharing ur config. It wasn't related to `dir_to_exclude`, did you have something inside option table before? The problem was something with the custom config you had there.
Yes you can add something like this:
```lua
enable_on = {
	"html",
	"javascriptreact",
	"typescriptreact",
}, -- set the file types you want the plugin to work on

```

**Comment by ricardoantonio** [comment] 2024-11-10 14:41
This was the config I had, as the lazy installation example in the readme page.
```lua
{
  name = 'html-css',
    option = {
    -- your configuration here
    },
  },
```

**Comment by Jezda1337** [comment] 2024-11-10 14:45
That was the reason for your error, you cannot have option with only a comment inside. Under the lazy section there is a configuration section which you can use to configure the plugin. [link.](https://github.com/Jezda1337/nvim-html-css?tab=readme-ov-file#-configuration)
Maybe I should merge this two section, to avoid conflicts like this.

**Comment by ricardoantonio** [comment] 2024-11-10 14:55
Yes, please, that would be very useful.

Just to clarify, so the plugin can't be added as a dependency of nvim-cmp?
It might also be a good idea to include a note specifying that it needs to be loaded after nvim-cmp, although with the installation example it should be clear. I just wanted to include it alongside the other cmp plugins.

**Comment by Jezda1337** [comment] 2024-11-10 14:58
Yes `html-css` plugin cannot be added as dependency of nvim-cmp. Thanks for suggestions, I will update `README.md`.

**Comment by ricardoantonio** [comment] 2024-11-10 15:00
Thank you! Now your plugin is working in my config! 
**Thanks for your great work!**

**Closed** 2024-11-10 15:01 UTC
